### ISSUE TITLE
Better animation support for offscreen cells

### ISSUE THREAD

**Issue by mrjjwright** [ButterKit/BTRCollectionView#5]
Animation works during layout changes as long as all cells are on screen but not when cells are brought from offscreen such as when the size or numbers of cells change.  The collection view needs to calculate it's next visible rect according to it's pending update list and bring in any needed offscreen cells into their before positions in this rect in a core animation transaction.  Then, it should apply the normal collection view updates in a subsequent animation transaction so that offscreen cells animate into their positions.  This currently is not done, which can be seen by toggling the size of a row in CollectionViewListLayout so that cells animate offscreen and onscreen (in and out of the visible rect).  The offscreen cells do not animate into place.

**Comment by jwilling** [comment]
Closing as this repository isn't supported any more. Thanks for raising this in the first place, though.
